import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Srpski kulturni centar",
    description: "Generated by create next app",
  };
 
export default async function LocaleLayout(props: {
    children: React.ReactNode;
    params: { locale: string };
  }) {
    const locale = (await props.params).locale;
  
    if (!routing.locales.includes(locale as any)) {
      notFound();
    }
  
    const messages = await getMessages();

    
  
 
  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <NextIntlClientProvider messages={messages}>
          {props.children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}